# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8   

    - name: Docker build
      run: docker build --tag redislabs/prophetgears:edge .

    - name: Docker run
      run: docker run -d -p 6379:6379 -it --rm redislabs/prophetgears:edge

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Load data
      run: python load.py 
    
    - name: Run prediction
      run: python gears.py --requirements ./predict_requirements.txt predict.py
